name: Build Zed for Windows

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Enable Long Paths in Git and Windows
        run: |
          git config --system core.longpaths true
          New-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.29.2'

      - name: Install Visual Studio Build Tools with Spectre libs
        run: |
          choco install visualstudio2022buildtools `
            visualstudio2022-workload-vctools `
            visualstudio2022-workload-nativedesktop `
            visualstudio2022componentgroup-native-desktop-core `
            microsoft-visualstudio-component-vc-spectre `
            --package-parameters "--includeRecommended --includeOptional" -y

      - name: Build Release
        run: cargo build --release

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows
          path: target/release/zed.exe
